export const SET_GLOBAL_USER = "USER/SET_GLOBAL";
export const DELETE_GLOBAL_USER = "USER/DELETE_USER";

export const SET_USUARIO_PROVISORIO = "SET_USUARIO_PROVISORIO";
export const SET_USER = "SET_USER";
